feat: ET-1426: Added Azure support and updated readme
dvla/opencommit pull request #2
Opened 2023-10-25 09:59 UTC by mattsalt123

Updated README.md with instructions for getting API key from OpenAI or Azure and added additional config options for OpenAI and Azure. Also, modified api.ts to handle different API types (OpenAI or Azure) based on the config.

2023-10-25 10:54 UTC, covolution requested changes
Can you link to the original pull request in the readme? https://github.com/di-sukharev/opencommit/pull/167

2023-10-25 10:54 UTC, covolution commented on src/api.ts
> +            'api-version': '2023-07-01-preview',
This needs to be a parameter in the config

2023-10-25 10:54 UTC, covolution commented on src/commands/config.ts
> +      'Must be 51 or 32 characters long'
perhaps in brackets (openai) or (azure)

2023-10-25 10:54 UTC, covolution commented on src/commands/config.ts
> +        'gpt4-613',
I think those are deployments rather than model names.

2023-10-26 14:25 UTC, covolution commented on src/api.ts
> +        break;
not needed

2023-10-26 14:25 UTC, covolution commented on src/commands/config.ts
> +        value.startsWith('sk-') || value.match(/^[a-z0-9]{32}$/),
what's the whitespace?

2023-10-26 14:25 UTC, covolution commented on src/commands/config.ts
> +        value.startsWith('sk-') || value.match(/^[a-z0-9]{32}$/),
regex should be a constant

2023-10-26 14:25 UTC, covolution commented on src/api.ts
> +let apiType = config?.OCO_OPENAI_API_TYPE || 'openai';
Should lets be constants?

2023-10-26 15:17 UTC, covolution approved these changes

2023-10-26 15:24 UTC, vestron286 approved these changes
Good job!

2023-10-26 15:25 UTC, merged